a=8
print(type(a))
x=8.0
y=3.33
z=8
u="abc"
print(type(x))
print(type(y))
print(type(z))
print(type(u),type(z))
b=2+3j
print(type(b))
print(isinstance(b,complex))
s="richa"
s.capitalize()
print(s.upper())
print(s.isalpha())
print(s.capitalize())
print(s.isalnum())
print(len(s))
v="hello, there, welcome, to, acad, view"
print(v.split())
print(v.split(","))
print(v[0])
a=[1,2,3,4]
print(a)
print(a[-1])
print(a[3])
l=["happy",2,"hello",3]
print(l[0][1])
print(l[1][2])
l2=["happy",[1,2,3]]
print(l2[1][2])